### ISSUE TITLE
Build bug

### ISSUE THREAD

**Issue by msimonc** [phiphou/webpack-vue-demo#5]
Hi, thanks for this project,

If I change a .vue file webstorm is watching and compiles ok, the browser refreshes without the change.
If I change a .tpl.pug file it works.

Either yarn or npm start
Either Mac or Windows

Thanks!

**Comment by phiphou** [comment]
Hi, 

I dont'use WebStorm, so I'm not able to reproduce this.

Can you please try this : 

- install `vue-hot-reload-api` with `npm install vue-hot-reload-api -D` 

- update the `package.json` with `"start": "cross-env NODE_ENV=development node ./config/dev-server --inline --hot"`

Please let me know if it resolves the issue.
